StrucInfo:
  struct:
    element: Au
    lattype: fcc
    latcont: 4.16
    facet: ['111']
    dope:
      Cu: [3]

Model:
  coads:
    - ['NH3','O',1,1]
    - ['NH2','OH',1,1]
    - ['N','N',1,1]
    - ['N','O',1,1]
    - ['N','NO',1,1]